#version: '3.8'
#
#services:
#
#  postgres:
#    image: postgres
#    container_name: postgres-db
#
#    environment:
#      POSTGRES_DB: employeedb
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: admin
#
#    ports:
#      - "5432:5432"
#
#
#  employee-app:
#    build: .
#    container_name: employee-app
#
#
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employeedb
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: admin
#
#
#
#    ports:
#      - "9090:8081"
#
#    depends_on:
#      - postgres